// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseProtoBuf.proto

package com.why.game.response;

public final class ResponseProtocolBuffer {
  private ResponseProtocolBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional int32 rank = 3;
    boolean hasRank();
    int getRank();
    
    // optional int32 gold = 4;
    boolean hasGold();
    int getGold();
    
    // optional int32 exp = 5;
    boolean hasExp();
    int getExp();
    
    // optional int32 diamond = 6;
    boolean hasDiamond();
    int getDiamond();
  }
  public static final class TestProto extends
      com.google.protobuf.GeneratedMessage
      implements TestProtoOrBuilder {
    // Use TestProto.newBuilder() to construct.
    private TestProto(Builder builder) {
      super(builder);
    }
    private TestProto(boolean noInit) {}
    
    private static final TestProto defaultInstance;
    public static TestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public TestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.why.game.response.ResponseProtocolBuffer.internal_static_ResponseProtocolBuffer_TestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.why.game.response.ResponseProtocolBuffer.internal_static_ResponseProtocolBuffer_TestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 rank = 3;
    public static final int RANK_FIELD_NUMBER = 3;
    private int rank_;
    public boolean hasRank() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRank() {
      return rank_;
    }
    
    // optional int32 gold = 4;
    public static final int GOLD_FIELD_NUMBER = 4;
    private int gold_;
    public boolean hasGold() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getGold() {
      return gold_;
    }
    
    // optional int32 exp = 5;
    public static final int EXP_FIELD_NUMBER = 5;
    private int exp_;
    public boolean hasExp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getExp() {
      return exp_;
    }
    
    // optional int32 diamond = 6;
    public static final int DIAMOND_FIELD_NUMBER = 6;
    private int diamond_;
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getDiamond() {
      return diamond_;
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      rank_ = 0;
      gold_ = 0;
      exp_ = 0;
      diamond_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rank_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gold_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, exp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, diamond_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rank_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gold_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, exp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, diamond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.why.game.response.ResponseProtocolBuffer.TestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.why.game.response.ResponseProtocolBuffer.TestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.why.game.response.ResponseProtocolBuffer.TestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.why.game.response.ResponseProtocolBuffer.internal_static_ResponseProtocolBuffer_TestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.why.game.response.ResponseProtocolBuffer.internal_static_ResponseProtocolBuffer_TestProto_fieldAccessorTable;
      }
      
      // Construct using com.why.game.response.ResponseProtocolBuffer.TestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.why.game.response.ResponseProtocolBuffer.TestProto.getDescriptor();
      }
      
      public com.why.game.response.ResponseProtocolBuffer.TestProto getDefaultInstanceForType() {
        return com.why.game.response.ResponseProtocolBuffer.TestProto.getDefaultInstance();
      }
      
      public com.why.game.response.ResponseProtocolBuffer.TestProto build() {
        com.why.game.response.ResponseProtocolBuffer.TestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.why.game.response.ResponseProtocolBuffer.TestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.why.game.response.ResponseProtocolBuffer.TestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.why.game.response.ResponseProtocolBuffer.TestProto buildPartial() {
        com.why.game.response.ResponseProtocolBuffer.TestProto result = new com.why.game.response.ResponseProtocolBuffer.TestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rank_ = rank_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.diamond_ = diamond_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.why.game.response.ResponseProtocolBuffer.TestProto) {
          return mergeFrom((com.why.game.response.ResponseProtocolBuffer.TestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.why.game.response.ResponseProtocolBuffer.TestProto other) {
        if (other == com.why.game.response.ResponseProtocolBuffer.TestProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasRank()) {
          setRank(other.getRank());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rank_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gold_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              exp_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              diamond_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional int32 rank = 3;
      private int rank_ ;
      public boolean hasRank() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRank() {
        return rank_;
      }
      public Builder setRank(int value) {
        bitField0_ |= 0x00000004;
        rank_ = value;
        onChanged();
        return this;
      }
      public Builder clearRank() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rank_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 gold = 4;
      private int gold_ ;
      public boolean hasGold() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getGold() {
        return gold_;
      }
      public Builder setGold(int value) {
        bitField0_ |= 0x00000008;
        gold_ = value;
        onChanged();
        return this;
      }
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gold_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 exp = 5;
      private int exp_ ;
      public boolean hasExp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getExp() {
        return exp_;
      }
      public Builder setExp(int value) {
        bitField0_ |= 0x00000010;
        exp_ = value;
        onChanged();
        return this;
      }
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exp_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 diamond = 6;
      private int diamond_ ;
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getDiamond() {
        return diamond_;
      }
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000020;
        diamond_ = value;
        onChanged();
        return this;
      }
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000020);
        diamond_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ResponseProtocolBuffer.TestProto)
    }
    
    static {
      defaultInstance = new TestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ResponseProtocolBuffer.TestProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseProtocolBuffer_TestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResponseProtocolBuffer_TestProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ResponseProtoBuf.proto\022\026ResponseProtoc" +
      "olBuffer\"_\n\tTestProto\022\n\n\002id\030\001 \001(\003\022\014\n\004nam" +
      "e\030\002 \001(\t\022\014\n\004rank\030\003 \001(\005\022\014\n\004gold\030\004 \001(\005\022\013\n\003e" +
      "xp\030\005 \001(\005\022\017\n\007diamond\030\006 \001(\005B/\n\025com.why.gam" +
      "e.responseB\026ResponseProtocolBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ResponseProtocolBuffer_TestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ResponseProtocolBuffer_TestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ResponseProtocolBuffer_TestProto_descriptor,
              new java.lang.String[] { "Id", "Name", "Rank", "Gold", "Exp", "Diamond", },
              com.why.game.response.ResponseProtocolBuffer.TestProto.class,
              com.why.game.response.ResponseProtocolBuffer.TestProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
